/* MarketMunchkin dashboard — single-page app over the JSON API. No build step, no dependencies. */
const $ = s => document.querySelector(s);
const esc = s => (s ?? '').toString().replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money = v => v == null ? '–' : (v < 0 ? '−' : '') + '$' + Math.abs(v).toFixed(2);
const pct = (v, d = 2) => v == null ? '' : (v >= 0 ? '+' : '−') + Math.abs(v).toFixed(d) + '%';
const cls = v => v > 0 ? 'up' : v < 0 ? 'dn' : '';
const hm = s => (s || '').slice(11, 16);
const dhm = s => (s || '').slice(5, 16).replace('T', ' ');
const css = n => getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const OCC = /^([A-Z]{1,6})(\d{6})([CP])(\d{8})$/;
const occ = s => { const m = OCC.exec(s || ''); return m ? { u: m[1], exp: `20${m[2].slice(0,2)}-${m[2].slice(2,4)}-${m[2].slice(4)}`, type: m[3], k: +m[4] / 1000, h: `${m[1]} ${m[2].slice(2,4)}/${m[2].slice(4)} ${+m[4]/1000}${m[3]}` } : null; };
const ICONS = {
  grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  layers: '<path d="M12 3l9 5-9 5-9-5 9-5z"/><path d="M3 13l9 5 9-5"/>', book: '<path d="M4 4h9a3 3 0 0 1 3 3v13H7a3 3 0 0 1-3-3V4z"/><path d="M16 7a3 3 0 0 1 3-3h1v13h-1"/>',
  brain: '<path d="M12 3a4 4 0 0 0-4 4v10a4 4 0 0 0 8 0V7a4 4 0 0 0-4-4z"/><path d="M8 9H6a2 2 0 0 0 0 4h2M16 9h2a2 2 0 0 1 0 4h-2"/>', sliders: '<path d="M4 7h10M18 7h2M4 17h4M12 17h8"/><circle cx="15" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',
  shield: '<path d="M12 3l7 3v6c0 4.5-3 8-7 9-4-1-7-4.5-7-9V6l7-3z"/>', up: '<path d="M12 19V5M6 11l6-6 6 6"/>', down: '<path d="M12 5v14M6 13l6 6 6-6"/>', check: '<path d="M5 12l4 4L19 6"/>',
  clock: '<circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/>', pulse: '<path d="M3 12h4l3-7 4 14 3-7h4"/>', chevron: '<path d="M15 6l-6 6 6 6"/>', search: '<circle cx="11" cy="11" r="6"/><path d="M20 20l-4.5-4.5"/>',
  flask: '<path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3"/>', sun: '<circle cx="12" cy="12" r="4"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M5.6 18.4L7 17M17 7l1.4-1.4"/>',
  moon: '<path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z"/>', monitor: '<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/>',
};
const icon = (n, s = 18, c = 'currentColor') => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${ICONS[n]}</svg>`;
const pill = (t, k = '', ic = null) => `<span class="pill ${k}">${ic ? icon(ic, 11) : ''}${esc(t)}</span>`;
const card = (title, body, aside = '', extra = '') => `<div class="card" ${extra}><h2>${esc(title)}<small>${aside}</small></h2>${body}</div>`;
async function j(u) { const r = await fetch(u); if (!r.ok) throw new Error(u + ' → HTTP ' + r.status); return r.json(); }
async function post(u, body) { const r = await fetch(u, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'munchkin' }, body: JSON.stringify(body || {}) }); if (!r.ok) { let d = {}; try { d = await r.json(); } catch (e) {} throw new Error(d.detail || ('HTTP ' + r.status)); } return r.json(); }

/* ---------- theme ---------- */
function applyTheme(mode) { try { localStorage.mm_theme = mode; } catch (e) {} const sys = matchMedia('(prefers-color-scheme: light)').matches; document.documentElement.dataset.theme = mode === 'system' ? (sys ? 'light' : 'dark') : mode; }
let themeMode = 'dark'; try { themeMode = localStorage.mm_theme || 'dark'; } catch (e) {} applyTheme(themeMode);
matchMedia('(prefers-color-scheme: light)').addEventListener('change', () => applyTheme(themeMode));

/* ---------- markdown (headings, lists, bold/italic/code, tables, paragraphs) ---------- */
function inline(s) { return esc(s).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/(^|[^*])\*([^*\n]+)\*/g, '$1<em>$2</em>'); }
function md(text) {
  const lines = (text || '').replace(/\r/g, '').split('\n'); const out = []; let i = 0;
  const flushP = buf => { if (buf.length) { out.push('<p>' + buf.map(inline).join(' ') + '</p>'); buf.length = 0; } };
  let p = [];
  while (i < lines.length) {
    const l = lines[i];
    if (/^\s*$/.test(l)) { flushP(p); i++; continue; }
    const h = /^(#{1,6})\s+(.*)$/.exec(l); if (h) { flushP(p); out.push(`<h3>${inline(h[2])}</h3>`); i++; continue; }
    if (/^\s*\|.*\|\s*$/.test(l)) { flushP(p); const rows = []; while (i < lines.length && /^\s*\|.*\|\s*$/.test(lines[i])) { rows.push(lines[i]); i++; }
      const cells = r => r.trim().replace(/^\||\|$/g, '').split('|').map(c => c.trim()); const body = rows.filter(r => !/^\s*\|?\s*:?-{2,}/.test(r));
      if (body.length) { const [hd, ...rest] = body; out.push('<table><tr>' + cells(hd).map(c => '<th>' + inline(c) + '</th>').join('') + '</tr>' + rest.map(r => '<tr>' + cells(r).map(c => '<td>' + inline(c) + '</td>').join('') + '</tr>').join('') + '</table>'); } continue; }
    if (/^\s*([-*•]|\d+[.)])\s+/.test(l)) { flushP(p); const ordered = /^\s*\d+[.)]/.test(l); const items = []; while (i < lines.length && /^\s*([-*•]|\d+[.)])\s+/.test(lines[i])) { items.push(lines[i].replace(/^\s*([-*•]|\d+[.)])\s+/, '')); i++; }
      out.push((ordered ? '<ol>' : '<ul>') + items.map(x => '<li>' + inline(x) + '</li>').join('') + (ordered ? '</ol>' : '</ul>')); continue; }
    p.push(l); i++;
  }
  flushP(p); return '<div class="md">' + out.join('') + '</div>';
}

/* ---------- charts (inline SVG) ---------- */
function lineChart(vals, w, h, color, base) {
  if (!vals.length) return '<div class="dim">no samples yet</div>';
  let lo = Math.min(...vals, base ?? Infinity), hi = Math.max(...vals, base ?? -Infinity); if (hi - lo < 1e-9) { hi = lo + 1; }
  const X = i => (i * w / Math.max(1, vals.length - 1)).toFixed(1), Y = v => (h - 4 - (v - lo) * (h - 8) / (hi - lo)).toFixed(1);
  const d = vals.map((v, i) => (i ? 'L' : 'M') + X(i) + ' ' + Y(v)).join(' ');
  return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" style="width:100%;height:${h}px;display:block"><path d="${d} L${w} ${h} L0 ${h}Z" fill="${color}" fill-opacity=".10"/>${base != null ? `<line x1="0" x2="${w}" y1="${Y(base)}" y2="${Y(base)}" stroke="${css('--base')}" />` : ''}<path d="${d}" fill="none" stroke="${color}" stroke-width="2" stroke-linejoin="round" vector-effect="non-scaling-stroke"/><circle cx="${X(vals.length-1)}" cy="${Y(vals[vals.length-1])}" r="5" fill="${color}" stroke="${css('--surf')}" stroke-width="2"/></svg>`;
}
function equityChart(points, w, h, base, range) {
  if (!points.length) return '<div class="dim">no samples yet</div>';
  const vals = points.map(p => p.equity); const padL = 8, padR = 56, padT = 10, padB = 22; const W = w - padL - padR, H = h - padT - padB;
  let lo = Math.min(...vals, base ?? Infinity), hi = Math.max(...vals, base ?? -Infinity); const span = Math.max(hi - lo, 0.5); lo -= span * 0.08; hi += span * 0.08;
  // x by actual time (sampling slows after the close), falling back to sample index if timestamps are missing
  const times = points.map(p => Date.parse((p.ts || '').replace(' ', 'T'))); const timed = times.every(t => !isNaN(t)) && times[times.length - 1] > times[0];
  const t0 = timed ? times[0] : 0, t1 = timed ? times[times.length - 1] : Math.max(1, vals.length - 1);
  const X = i => (padL + ((timed ? times[i] : i) - t0) * W / (t1 - t0)).toFixed(1), Y = v => (padT + H - (v - lo) * H / (hi - lo)).toFixed(1);
  const d = vals.map((v, i) => (i ? 'L' : 'M') + X(i) + ' ' + Y(v)).join(' '); const col = css('--series'), grid = css('--grid'), dim = css('--dim');
  let out = '';
  // price gridlines: 4 nice steps
  const rawStep = (hi - lo) / 4, mag = Math.pow(10, Math.floor(Math.log10(rawStep))), step = [1, 2, 2.5, 5, 10].map(m => m * mag).find(s => s >= rawStep) || rawStep;
  for (let v = Math.ceil(lo / step) * step; v <= hi; v += step) out += `<line x1="${padL}" x2="${padL + W}" y1="${Y(v)}" y2="${Y(v)}" stroke="${grid}"/><text x="${padL + W + 6}" y="${+Y(v) + 3.5}" font-size="10" fill="${dim}" style="font-family:var(--mono)">$${v.toFixed(step < 1 ? 2 : 0)}</text>`;
  // time ticks: hourly for 1d, per day for 1w, weekly beyond. points carry ts (ISO, ET)
  const ticks = []; let lastKey = null;
  points.forEach((p, i) => { const ts = p.ts || ''; const key = range === '1d' ? ts.slice(0, 13) : range === '1w' ? ts.slice(0, 10) : ts.slice(0, 10); if (key !== lastKey) { lastKey = key; if (range === '1d') ticks.push([i, ts.slice(11, 13) + ':00']); else if (range === '1w') ticks.push([i, ts.slice(5, 10)]); else if (new Date(ts).getDay() === 1) ticks.push([i, ts.slice(5, 10)]); } });
  const maxTicks = Math.max(3, Math.floor(W / 70)); let keep = ticks.length > maxTicks ? ticks.filter((_, k) => k % Math.ceil(ticks.length / maxTicks) === 0) : ticks;
  let lastX = -1e9; keep = keep.filter(([i]) => { const x = +X(i); if (x - lastX < 46) return false; lastX = x; return true; });
  keep.forEach(([i, lab]) => { if (range === '1d' && i === 0) lab = (points[0].ts || '').slice(11, 16); out += `<line x1="${X(i)}" x2="${X(i)}" y1="${padT}" y2="${padT + H}" stroke="${grid}" stroke-dasharray="2 3"/><text x="${X(i)}" y="${h - 6}" text-anchor="middle" font-size="10" fill="${dim}" style="font-family:var(--mono)">${esc(lab)}</text>`; });
  if (base != null) out += `<line x1="${padL}" x2="${padL + W}" y1="${Y(base)}" y2="${Y(base)}" stroke="${css('--base')}" stroke-dasharray="4 3"/><text x="${padL + 4}" y="${+Y(base) - 4}" font-size="10" fill="${dim}">start $${base}</text>`;
  out += `<path d="${d} L${X(vals.length - 1)} ${padT + H} L${padL} ${padT + H}Z" fill="${col}" fill-opacity=".10"/><path d="${d}" fill="none" stroke="${col}" stroke-width="2" stroke-linejoin="round"/><circle cx="${X(vals.length - 1)}" cy="${Y(vals[vals.length - 1])}" r="5" fill="${col}" stroke="${css('--surf')}" stroke-width="2"/>`;
  return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;height:100%;display:block">${out}</svg>`;
}
function sparkLevels(vals, w, h, levels, entryI, entryPx) {
  if (!vals.length) return '';
  let lo = Math.min(...vals), hi = Math.max(...vals); for (const l of levels) { lo = Math.min(lo, l.px); hi = Math.max(hi, l.px); } lo -= 0.2; hi += 0.2;
  const X = i => (i * w / Math.max(1, vals.length - 1)).toFixed(1), Y = v => (h - 4 - (v - lo) * (h - 8) / (hi - lo)).toFixed(1);
  const d = vals.map((v, i) => (i ? 'L' : 'M') + X(i) + ' ' + Y(v)).join(' ');
  return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;height:${h}px;display:block;overflow:visible"><path d="${d}" fill="none" stroke="${css('--fg')}" stroke-width="2" stroke-linejoin="round"/>${levels.map(l => `<line x1="0" x2="${w}" y1="${Y(l.px)}" y2="${Y(l.px)}" stroke="${l.c}"/><text x="${w-2}" y="${Y(l.px)-3}" text-anchor="end" font-size="10" fill="${l.c}">${esc(l.label)}</text>`).join('')}${entryI != null ? `<circle cx="${X(entryI)}" cy="${Y(entryPx)}" r="5" fill="${css('--dec')}" stroke="${css('--surf')}" stroke-width="2"/>` : ''}<circle cx="${X(vals.length-1)}" cy="${Y(vals[vals.length-1])}" r="4" fill="${css('--fg')}" stroke="${css('--surf')}" stroke-width="2"/></svg>`;
}
function candles(bars, w, h, levels, marker) {
  if (!bars.length) return '<div class="dim">no bars</div>';
  const volH = 44, ph = h - volH - 10; let lo = Math.min(...bars.map(b => b.l)), hi = Math.max(...bars.map(b => b.h));
  for (const l of levels) { lo = Math.min(lo, l.px); hi = Math.max(hi, l.px); } lo -= (hi - lo) * 0.04; hi += (hi - lo) * 0.04;
  const n = bars.length, slot = w / n, bw = Math.max(3, Math.min(10, slot * 0.55)); const Y = v => (ph - (v - lo) * ph / (hi - lo)).toFixed(1);
  const up = css('--up'), dn = css('--dn'), surf = css('--surf'), dim = css('--dim'), grid = css('--grid'); let out = '';
  for (let k = 0; k < 4; k++) { const v = lo + (hi - lo) * k / 3; out += `<line x1="0" x2="${w}" y1="${Y(v)}" y2="${Y(v)}" stroke="${grid}"/><text x="${w-2}" y="${Y(v)-3}" text-anchor="end" font-size="10" fill="${dim}">${v.toFixed(0)}</text>`; }
  const vmax = Math.max(...bars.map(b => b.v || 0), 1);
  bars.forEach((b, i) => { const x = (i * slot + slot / 2).toFixed(1), c = b.c >= b.o ? up : dn, top = Y(Math.max(b.o, b.c)), bot = Y(Math.min(b.o, b.c)); out += `<line x1="${x}" x2="${x}" y1="${Y(b.h)}" y2="${Y(b.l)}" stroke="${c}"/><rect x="${(x - bw/2).toFixed(1)}" y="${top}" width="${bw}" height="${Math.max(1.5, bot - top)}" rx="1" fill="${c}"/>`; const vh = Math.max(1, (b.v || 0) / vmax * (volH - 6)); out += `<rect x="${(x - bw/2).toFixed(1)}" y="${h - vh}" width="${bw}" height="${vh}" rx="1" fill="${c}" fill-opacity=".35"/>`; });
  for (const l of levels) { const y = Y(l.px); out += `<line x1="0" x2="${w}" y1="${y}" y2="${y}" stroke="${l.c}"/><rect x="0" y="${y-9}" width="96" height="18" rx="4" fill="${surf}" stroke="${l.c}"/><text x="6" y="${+y+4}" font-size="10.5" fill="${l.c}">${esc(l.label)}</text>`; }
  if (marker) { const x = (marker.i * slot + slot / 2).toFixed(1), y = Y(marker.px); out += `<circle cx="${x}" cy="${y}" r="6" fill="${css('--dec')}" stroke="${surf}" stroke-width="2"/><rect x="${x-64}" y="${+y+8}" width="56" height="16" rx="4" fill="${surf}" stroke="${css('--dec')}"/><text x="${x-36}" y="${+y+20}" text-anchor="middle" font-size="10.5" fill="${css('--fg')}">${esc(marker.label)}</text>`; }
  const step = Math.max(1, Math.round(n / 6)); for (let i = 0; i < n; i += step) out += `<text x="${(i*slot+slot/2).toFixed(1)}" y="${h+12}" text-anchor="middle" font-size="10" fill="${dim}">${esc((bars[i].t || '').slice(5))}</text>`;
  return `<svg viewBox="0 0 ${w} ${h+16}" style="width:100%;display:block;overflow:visible">${out}</svg>`;
}
function gauge(score, w = 150) { const r = w / 2 - 10, cx = w / 2, cy = w / 2, ang = Math.PI * (1 - score / 100), ex = cx + r * Math.cos(ang), ey = cy - r * Math.sin(ang), large = score > 50 ? 1 : 0; const col = score <= 40 ? css('--dn') : score >= 60 ? css('--up') : css('--gold');
  return `<svg viewBox="0 0 ${w} ${w/2+14}" style="width:${w}px;display:block"><path d="M${cx-r} ${cy} A${r} ${r} 0 0 1 ${cx+r} ${cy}" fill="none" stroke="${css('--surf2')}" stroke-width="10" stroke-linecap="round"/><path d="M${cx-r} ${cy} A${r} ${r} 0 ${large} 1 ${ex.toFixed(1)} ${ey.toFixed(1)}" fill="none" stroke="${col}" stroke-width="10" stroke-linecap="round"/><text x="${cx}" y="${cy-6}" text-anchor="middle" font-size="30" font-weight="600" fill="${css('--fg')}" style="font-family:var(--disp)">${score}</text><text x="${cx}" y="${cy+12}" text-anchor="middle" font-size="11" fill="${css('--muted')}" style="font-family:var(--sans)">of 100</text></svg>`; }
function payoff(cfg, w, h) {
  const { type = 'C', longK, shortK = null, debit, spot, em = null, qty = 1 } = cfg; const mult = 100 * qty;
  const span = shortK ? Math.abs(shortK - longK) * 2.5 : (longK * 0.12); const lo = Math.min(longK, spot) - span, hi = Math.max(shortK || longK, spot) + span;
  const X = p => ((p - lo) * w / (hi - lo)).toFixed(1); const val = p => { const dir = type === 'C' ? 1 : -1; let v = Math.max(0, dir * (p - longK)); if (shortK) v -= Math.max(0, dir * (p - shortK)); return (v - debit) * mult; };
  const ys = [lo, longK, shortK || longK, hi].map(val); const ymin = Math.min(...ys) - 20, ymax = Math.max(...ys) + 20; const Y = v => (h - 14 - (v - ymin) * (h - 28) / (ymax - ymin)).toFixed(1);
  const pts = [lo, longK, ...(shortK ? [shortK] : []), hi]; const d = pts.map((p, i) => (i ? 'L' : 'M') + X(p) + ' ' + Y(val(p))).join(' '); const be = type === 'C' ? longK + debit : longK - debit;
  return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;display:block;overflow:visible">${em ? `<rect x="${X(spot*(1-em/100))}" y="0" width="${(X(spot*(1+em/100)) - X(spot*(1-em/100))).toFixed(1)}" height="${h-14}" fill="${css('--series')}" fill-opacity=".10"/><text x="${+X(spot*(1-em/100))+4}" y="24" font-size="10" fill="${css('--series')}">expected move ±${em}%</text>` : ''}<line x1="0" x2="${w}" y1="${Y(0)}" y2="${Y(0)}" stroke="${css('--base')}"/><path d="${d}" fill="none" stroke="${css('--gold')}" stroke-width="2" stroke-linejoin="round"/><line x1="${X(spot)}" x2="${X(spot)}" y1="0" y2="${h-14}" stroke="${css('--fg')}"/><text x="${+X(spot)+4}" y="10" font-size="10" fill="${css('--fg')}">spot ${spot}</text><circle cx="${X(be)}" cy="${Y(0)}" r="5" fill="${css('--gold')}" stroke="${css('--surf')}" stroke-width="2"/><text x="${+X(be)+8}" y="${+Y(0)+14}" font-size="10" fill="${css('--muted')}">breakeven ${be.toFixed(2)}</text><text x="2" y="${+Y(val(lo))-6}" font-size="10" fill="${css('--dn')}">max loss ${money(val(lo) < val(hi) ? val(lo) : val(hi))}</text><text x="${w-2}" y="${+Y(val(hi))-6}" text-anchor="end" font-size="10" fill="${css('--up')}">${shortK ? 'max gain ' + money(Math.max(val(lo), val(hi))) : (type === 'C' ? 'unlimited upside' : 'gain to zero')}</text>${[lo, longK, shortK, hi].filter(x => x).map(p => `<text x="${X(p)}" y="${h-2}" text-anchor="middle" font-size="10" fill="${css('--dim')}">${p.toFixed(0)}</text>`).join('')}</svg>`;
}
const nodeColor = k => ({ thinking: css('--think'), tool: css('--tool'), decision: css('--dec'), blocked: css('--dn'), final: css('--up') }[k] || css('--muted'));
function ribbon(nodes, w, compact) {
  if (!nodes || !nodes.length) return '<div class="dim">no trace</div>';
  compact = compact || innerWidth < 900;
  const h = compact ? 60 : 96, n = nodes.length, slot = w / n; let out = `<line x1="0" x2="${w}" y1="${h/2}" y2="${h/2}" stroke="${css('--line')}"/>`;
  nodes.forEach((nd, i) => { const x = (i * slot + slot / 2).toFixed(1), y = h / 2, c = nodeColor(nd.k), r = ['decision', 'blocked', 'final'].includes(nd.k) ? 7 : 5;
    if (nd.k === 'thinking') out += `<circle cx="${x}" cy="${y}" r="${9 + Math.min(8, nd.n || 0)}" fill="${c}" fill-opacity=".18"/>`;
    out += `<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" stroke="${css('--surf')}" stroke-width="2"><title>${esc(nd.t || nd.k)}</title></circle>`;
    if (nd.k === 'blocked') out += `<path d="M${x-3} ${y-3}l6 6M${+x+3} ${y-3}l-6 6" stroke="${css('--surf')}" stroke-width="1.6" stroke-linecap="round"/>`;
    if (nd.k === 'decision' || nd.k === 'final') out += `<path d="M${x-3.5} ${y}l2.5 2.5 4.5-5" fill="none" stroke="${css('--surf')}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>`;
    if (!compact && nd.k !== 'tool' && nd.k !== 'thinking') out += `<text x="${x}" y="${i % 2 ? y - 16 : y + 22}" text-anchor="middle" font-size="9.5" fill="${css('--muted')}" style="font-family:var(--sans)">${esc((nd.t || nd.k).replace(/_/g, ' ').slice(0, 16))}</text>`; });
  return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;height:${h}px;display:block;overflow:hidden">${out}</svg>`;
}
const legend = () => `<div class="legend">${[['thinking', '--think'], ['tool call', '--tool'], ['decision', '--dec'], ['blocked', '--dn'], ['summary', '--up']].map(([n, c]) => `<span><i style="background:${css(c)}"></i>${n}</span>`).join('')}</div>`;
function hbars(rows, key, fmt) { const mx = Math.max(...rows.map(r => Math.abs(r[key])), 0.01); return rows.map(r => `<div style="display:grid;grid-template-columns:150px 1fr 64px;gap:10px;align-items:center;padding:4px 0"><span style="font-size:12px">${esc(r.label)}</span><div style="position:relative;height:8px;background:var(--surf2);border-radius:4px"><div style="position:absolute;top:0;height:8px;border-radius:4px;background:${r[key] >= 0 ? css('--up') : css('--dn')};left:${r[key] >= 0 ? 50 : 50 - Math.abs(r[key]) / mx * 50}%;width:${Math.abs(r[key]) / mx * 50}%"></div></div><span class="mono ${cls(r[key])}" style="font-size:11px;text-align:right">${fmt(r[key])}</span></div>`).join(''); }

/* ---------- chrome ---------- */
const NAV = [['overview', 'grid', 'Overview'], ['positions', 'layers', 'Positions'], ['sessions', 'pulse', 'Sessions'], ['brain', 'brain', 'Brain'], ['journal', 'book', 'Journal'], ['config', 'sliders', 'Config']];
let state = { style: 'balanced', daemon: 'unknown', halted: false };
function renderNav(active) {
  $('#rail').innerHTML = `<img src="/assets/mascot-48.png?v=4" alt="">` + NAV.map(([r, i, l]) => `<a href="#/${r}" class="${r === active ? 'on' : ''}">${icon(i, 20)}<span>${l}</span></a>`).join('') + `<div class="live"><span class="dot ${state.daemon === 'active' && !state.halted ? '' : 'off'}"></span><span>${state.halted ? 'halted' : state.daemon}</span></div>`;
  $('#tabs').innerHTML = NAV.map(([r, i, l]) => `<a href="#/${r}" class="${r === active ? 'on' : ''}">${icon(i, 18)}<span>${l}</span></a>`).join('');
}
function topbar(title, sub) {
  const styles = ['defensive', 'balanced', 'aggressive'];
  return `<div class="topbar"><div class="left"><span class="wordmark">Market<span>Munchkin</span></span><span class="vsep"></span><span class="title">${esc(title)}</span><span class="muted" style="font-size:12px">${sub}</span></div>
  <div class="right"><span class="muted" style="font-size:12px;display:inline-flex;align-items:center;gap:6px"><span class="dot ${state.daemon === 'active' ? '' : 'off'}"></span><span id="next-session">daemon ${esc(state.daemon)}</span></span>
  <span style="display:inline-flex;align-items:center;gap:8px"><span class="dim" style="font-size:11px;letter-spacing:.06em;text-transform:uppercase">Style</span><span class="seg">${styles.map(s => `<button class="st-${s} ${s === state.style ? 'on' : ''}" onclick="setStyle('${s}')">${s[0].toUpperCase() + s.slice(1)}</button>`).join('')}</span></span>
  <span class="seg">${[['dark', 'moon'], ['light', 'sun'], ['system', 'monitor']].map(([m, i]) => `<button class="${themeMode === m ? 'on' : ''}" title="${m}" onclick="themeMode='${m}';applyTheme('${m}');route()">${icon(i, 13)}</button>`).join('')}</span>
  <button class="halt" onclick="armKill()">${icon('shield', 14)}${state.halted ? 'Resume' : 'Halt'}</button></div></div><div id="killconfirm"></div>`;
}
async function setStyle(s) { if (s === state.style) return; if (!confirm(`Switch trading style to ${s}? It applies from the next session.`)) return; try { await post('/api/style', { style: s }); state.style = s; route(); } catch (e) { alert(e.message); } }
let killTimer = null;
function armKill() { const box = $('#killconfirm'); if (!box) return; clearTimeout(killTimer); const action = state.halted ? 'resume' : 'halt'; box.innerHTML = `<div class="confirm"><b>${action === 'halt' ? 'Halt new entries?' : 'Resume trading?'}</b> <span class="muted" style="font-size:12px">${action === 'halt' ? 'Exits, resting stops and the watcher keep running.' : ''} This window closes in 8 s.</span><div style="display:flex;gap:8px;margin-top:8px"><button class="btn ${action === 'halt' ? 'dngr' : 'pri'}" onclick="doKill('${action}')">Yes, ${action}</button><button class="btn" onclick="$('#killconfirm').innerHTML=''">Cancel</button></div></div>`; killTimer = setTimeout(() => { box.innerHTML = ''; }, 8000); }
async function doKill(action) { clearTimeout(killTimer); try { const d = await post('/api/halt', { action }); state.halted = d.halted; route(); } catch (e) { alert(e.message); } }

/* ---------- views ---------- */
function dial(d, compact) {
  const pos = d.score >= 0, wpc = Math.abs(d.score) * 50, col = d.score > 0.15 ? css('--up') : d.score < -0.15 ? css('--dn') : css('--gold');
  return `<div class="dial"><div class="h"><b>${esc(d.label)}</b><span>${d.score > 0.15 ? 'tailwind' : d.score < -0.15 ? 'headwind' : 'neutral'}</span></div><div class="track"><i style="background:${col};left:${pos ? 50 : 50 - wpc}%;width:${Math.max(2, wpc)}%"></i></div><div class="v">${esc(d.value)}</div>${compact ? '' : `<div class="n">${esc(d.note)}</div>`}</div>`;
}
function eventChips(evs) { return evs && evs.length ? `<div class="events">${evs.map(e => `<span class="ev">${icon(e.kind === 'fed' ? 'pulse' : 'clock', 12, e.kind === 'fed' ? css('--gold') : css('--dim'))}<b>${e.days === 0 ? 'today' : e.days === 1 ? 'tomorrow' : 'in ' + e.days + 'd'}</b><span>${esc(e.title)}</span></span>`).join('')}</div>` : ''; }
function worldMini(reg, w) {
  const dials = (w.dials || []).slice(0, 8);
  const vix = w.vix && w.vix.vix != null ? `VIX <span class="mono" style="color:var(--fg)">${w.vix.vix}</span> <span class="mono ${cls(w.vix.vix_chg_1d_pct)}">${pct(w.vix.vix_chg_1d_pct)}</span>` : '';
  return `<div style="display:flex;flex-direction:column;gap:12px;cursor:pointer" onclick="location.hash='#/brain'"><div style="display:flex;gap:16px;align-items:center">${gauge(reg.score, 130)}<div><div class="disp" style="font-size:22px">${esc(reg.label)}</div><div class="muted" style="font-size:12px">${vix}</div><div class="dim" style="font-size:11px">${dials.filter(d => d.score > 0.15).length} tailwinds · ${dials.filter(d => d.score < -0.15).length} headwinds · open the Brain for the brief</div></div></div><div class="dials compact">${dials.map(d => dial(d, true)).join('')}</div>${eventChips((w.next_events || []).slice(0, 3))}</div>`;
}
async function overview(v) {
  const [o, eq, sess, w] = await Promise.all([j('/api/overview'), j('/api/equity?range=' + (state.range || '1d')), j('/api/sessions?limit=1'), j('/api/world').catch(() => ({}))]);
  state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('overview'); const r = o.risk;
  const running = sess[0] && !sess[0].ended_at ? sess[0] : null;
  const tot = r.virtual_equity - o.starting_capital; const eqSvg = `<div id="eqchart" style="flex:1;min-height:200px"></div>`;
  const sparks = await Promise.all(o.positions.map(p => j('/api/spark/' + encodeURIComponent(p.raw)).catch(() => null)));
  const posHtml = o.positions.length ? o.positions.map((p, i) => { const sp = sparks[i]; const lv = []; if (p.stop) lv.push({ label: 'stop ' + p.stop, px: p.stop, c: css('--dn') }); const a = o.armed.find(x => x.symbol === p.raw); if (a) lv.push({ label: 'arm ' + a.trigger_price, px: a.trigger_price, c: css('--gold') });
    return `<div class="row" style="display:grid;grid-template-columns:1.1fr 1fr;gap:18px;align-items:center;cursor:pointer" onclick="location.hash='#/positions/${esc(p.raw)}'"><div style="display:flex;flex-direction:column;gap:6px"><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap"><span class="sym">${esc(p.symbol)}</span>${pill(p.raw.length > 6 ? 'option' : 'stock')}${p.grade ? pill(p.grade, p.grade === 'confirmed' ? 'up' : 'gold', p.grade === 'confirmed' ? 'check' : null) : ''}${p.resting_stop === 'NONE' ? pill('no resting stop', 'dn') : pill('stop resting', '', 'shield')}</div><div class="mono muted" style="font-size:12px">${p.qty} @ ${p.avg_entry} · last ${p.last} · <span class="${cls(p.pnl)}">${money(p.pnl)} ${pct(p.pnl_pct)}</span></div><div class="muted" style="font-size:12px">${esc((p.thesis || '').slice(0, 170))}</div><div class="muted" style="font-size:11px;display:flex;gap:14px"><span>stop <span class="mono dn">${p.stop ?? '–'}</span></span><span>target <span class="mono up">${p.target ?? '–'}</span></span></div></div>${sp && sp.closes && sp.closes.length ? sparkLevels(sp.closes, 300, 90, lv, null, null) : ''}</div>`; }).join('') : '<div class="dim">flat</div>';
  const armedHtml = o.armed.length ? o.armed.map(a => { const dist = a.last ? (a.direction === 'above' ? (a.trigger_price / a.last - 1) : (1 - a.trigger_price / a.last)) * 100 : null; const expr = a.expression || 'stock';
    return `<div class="row" style="display:grid;grid-template-columns:90px 1fr 150px;gap:12px;align-items:center;cursor:pointer" onclick="location.hash='#/positions/${esc(a.symbol)}'"><div style="display:flex;align-items:center;gap:8px">${icon(a.direction === 'above' ? 'up' : 'down', 14, expr === 'stock' ? css('--series') : css('--gold'))}<span class="sym sm">${esc(a.symbol)}</span></div><div><div class="mono" style="font-size:12px">${a.direction} ${a.trigger_price} · $${a.notional} <span class="muted">· ${esc(expr.replace('_', ' '))}</span></div><div class="muted" style="font-size:11px">${a.not_before ? 'not before ' + dhm(a.not_before) + ' · ' : ''}${a.spy_min_chg_pct != null ? 'SPY ≥ ' + a.spy_min_chg_pct + '% · ' : ''}${esc(a.catalyst_grade)}</div></div>${dist != null ? `<div style="display:flex;align-items:center;gap:8px"><div class="bar" style="width:90px"><i style="width:${Math.min(100, Math.abs(dist) / 3 * 100)}%"></i></div><span class="mono muted" style="font-size:11px">${Math.abs(dist).toFixed(1)}% away</span></div>` : '<span class="dim" style="font-size:11px">no quote</span>'}</div>`; }).join('') : '<div class="dim">none armed</div>';
  const ls = o.last_session;
  v.innerHTML = topbar('Overview', `${o.now.slice(0, 16)} ET · ${r.market_open ? 'market open' : 'market closed'}`) + (o.stale ? `<div class="card" style="border-color:var(--dn);padding:10px 14px;font-size:12.5px"><b class="dn">Broker API errors.</b> Showing the last good snapshot from ${esc(o.stale_since)}. Resting stops live at the broker and keep working. <span class="mono dim">${esc(o.broker_error)}</span></div>` : '') +
    `<div class="grid g21">${card('Equity', `<div style="display:flex;flex-direction:column;gap:8px;flex:1"><div style="display:flex;align-items:baseline;gap:14px;flex-wrap:wrap"><span class="hero">${money(r.virtual_equity)}</span><span class="mono ${cls(tot)}" style="font-size:13px">${tot >= 0 ? '▲' : '▼'} ${money(Math.abs(tot))} all-time</span><span class="mono ${cls(r.daily_pnl)}" style="font-size:13px">${r.daily_pnl >= 0 ? '▲' : '▼'} ${money(Math.abs(r.daily_pnl))} today</span><span class="muted" style="font-size:12px">buying power <span class="mono" style="color:var(--fg)">${money(r.buying_power_now)}</span> settled</span></div>${eqSvg}<div style="display:flex;justify-content:space-between;align-items:center"><span class="mono dim" style="font-size:11px">${eq.points.length ? esc(eq.points[0].t) + ' — ' + esc(eq.points[eq.points.length-1].t) + ' · ' + eq.points.length + ' samples' : ''}</span><span class="seg">${['1d', '1w', '1m', '3m'].map(x => `<button class="${(state.range || '1d') === x ? 'on' : ''}" onclick="state.range='${x}';route()">${x}</button>`).join('')}</span></div></div>`, 'since ' + (eq.points[0] ? esc(eq.points[0].ts.slice(0, 10)) : ''))}
    ${card('State of the world', o.regime ? worldMini(o.regime, w) : '<div class="dim">screener not built yet</div>', 'breadth · sectors · VIX')}</div>
    <div class="grid g12">${card('Positions', posHtml, `${r.positions_count} of ${o.max_positions}`)}${card('Armed entries', armedHtml, 'watcher executes within a minute of the trigger')}</div>
    ${card('Agent', ls ? `<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px"><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap"><a href="#/sessions/${ls.id}" class="disp" style="font-size:16px;color:var(--fg);text-decoration:none">Session #${ls.id}</a>${pill(ls.phase)}<span class="muted" style="font-size:12px">${esc((ls.actions || '').replace(/[*#]/g, '').slice(0, 140))}</span></div>${legend()}</div>${ribbon(ls.nodes, 1190, false)}` : '<div class="dim">no sessions yet</div>', `${o.cadence.continuous ? 'continuous' : 'every ' + o.cadence.interval_min + ' min'} · ${o.sessions_today} sessions today${running ? ' · <span class="gold">running #' + running.id + '</span>' : ''}`)}
    <div class="grid g11">${card('Risk', `<div class="mono muted" style="font-size:12px;display:flex;flex-direction:column;gap:4px"><div>per-position cap <span style="color:var(--fg)">${money(r.max_position_notional)}</span> · options budget <span style="color:var(--fg)">${money(r.max_new_options_premium)}</span></div><div>unsettled <span style="color:var(--fg)">${money(r.unsettled_proceeds)}</span> until next session · day trades ${r.day_trades_used_5d}</div><div>loss breaker ${r.daily_loss_breached ? '<span class="dn">TRIPPED</span>' : '<span class="up">ok</span>'} · ${r.restrictions.length ? '<span class="gold">' + esc(r.restrictions.join('; ')) + '</span>' : 'no restrictions'}</div><div>realized today <span class="${cls(o.realized_today)}">${money(o.realized_today)}</span> · all-time <span class="${cls(o.realized_total)}">${money(o.realized_total)}</span></div></div>`, pill(o.style, 'st-' + o.style))}
    ${card('Activity', o.events.length ? o.events.slice(0, 8).map(e => `<div style="display:flex;gap:10px;align-items:baseline;font-size:12px"><span class="mono dim" style="font-size:11px;min-width:36px">${hm(e.ts)}</span>${pill(e.kind, e.kind === 'event' ? 'acc' : e.kind === 'error' ? 'dn' : e.kind === 'action' ? 'gold' : '')}<span class="muted">${esc(e.text.slice(0, 120))}</span></div>`).join('') : '<div class="dim">nothing yet</div>', o.tasks_open + ' open tasks')}</div>`;
  const drawEq = () => { const el = $('#eqchart'); if (!el) return; const W = Math.max(320, el.clientWidth), H = Math.max(200, el.clientHeight); el.innerHTML = equityChart(eq.points, W, H, o.starting_capital, state.range || '1d'); };
  requestAnimationFrame(drawEq); state._eqResize && removeEventListener('resize', state._eqResize); state._eqResize = drawEq; addEventListener('resize', drawEq);
  if (o.last_session_end && !running) { const eta = new Date(o.last_session_end).getTime() + o.cadence.min_gap_s * 1000 - Date.now(); const el = $('#next-session'); if (el) el.textContent = eta > 0 ? `next session in ${Math.floor(eta / 60000)}:${String(Math.floor(eta % 60000 / 1000)).padStart(2, '0')}` : (r.market_open ? 'next session due' : 'off hours · ' + state.daemon); }
}
async function positions(v) {
  const o = await j('/api/overview'); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('positions');
  v.innerHTML = topbar('Positions', `${o.risk.positions_count} held · ${o.armed.length} armed`) + card('Held', o.positions.length ? o.positions.map(p => `<div class="row" style="cursor:pointer;align-items:center" onclick="location.hash='#/positions/${esc(p.raw)}'"><div><span class="sym">${esc(p.symbol)}</span> ${pill(p.raw.length > 6 ? 'option' : 'stock')} <div class="mono muted" style="font-size:12px">${p.qty} @ ${p.avg_entry} · last ${p.last} · stop ${p.stop ?? '–'} · target ${p.target ?? '–'}</div></div><div style="text-align:right"><div class="mono ${cls(p.pnl)}" style="font-size:18px">${money(p.pnl)}</div><div class="mono muted" style="font-size:12px">${pct(p.pnl_pct)}</div></div></div>`).join('') : '<div class="dim">flat</div>') + card('Armed entries', o.armed.length ? o.armed.map(a => `<div class="row" style="cursor:pointer" onclick="location.hash='#/positions/${esc(a.symbol)}'"><div><span class="sym sm">${esc(a.symbol)}</span> ${pill((a.expression || 'stock').replace('_', ' '), (a.expression || 'stock') === 'stock' ? '' : 'gold')} <div class="mono muted" style="font-size:12px">${a.direction} ${a.trigger_price} · $${a.notional} · stop ${a.stop_price} · target ${a.target_price}</div><div class="muted" style="font-size:12px">${esc((a.thesis || '').slice(0, 160))}</div></div>${pill(a.catalyst_grade, a.catalyst_grade === 'confirmed' ? 'up' : 'gold')}</div>`).join('') : '<div class="dim">none</div>');
}
async function position(v, sym) {
  const [o, d] = await Promise.all([j('/api/overview'), j('/api/positions/' + encodeURIComponent(sym))]); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('positions');
  const p = d.position, q = d.quote || {}; const levels = []; if (p && p.exits && p.exits.stop_level) levels.push({ label: 'stop ' + p.exits.stop_level, px: +p.exits.stop_level, c: css('--dn') }); if (p && p.exits && p.exits.target_level) levels.push({ label: 'target ' + p.exits.target_level, px: +p.exits.target_level, c: css('--up') }); if (d.armed) levels.push({ label: 'arm ' + d.armed.trigger_price, px: +d.armed.trigger_price, c: css('--gold') });
  let marker = null; const lastBuy = [...(d.fills || [])].reverse().find(f => f.side === 'buy'); if (lastBuy && d.bars_daily.length) { const day = (lastBuy.ts || '').slice(0, 10); let i = d.bars_daily.findIndex(b => b.t === day); if (i < 0) i = d.bars_daily.length - 1; marker = { i, px: +lastBuy.price, label: 'buy ' + (+lastBuy.price).toFixed(2) }; }
  const ladder = []; if (p && p.exits && p.exits.target_level) ladder.push([css('--up'), 'Target · take profit', `${p.exits.target_level} · watcher wakes the agent`, 'watched', 'up']); if (d.armed) ladder.push([css('--gold'), `Armed · ${(d.armed.expression || 'stock').replace('_', ' ')} $${d.armed.notional}`, `fires ${d.armed.direction} ${d.armed.trigger_price}${d.armed.not_before ? ' after ' + dhm(d.armed.not_before) : ''}${d.armed.spy_min_chg_pct != null ? ' if SPY ≥ ' + d.armed.spy_min_chg_pct + '%' : ''}`, 'armed', 'gold']); if (q.price) ladder.push([css('--fg'), `Last · ${q.price}`, `${esc(q.price_time || '')} · ${esc(q.price_src || '')}`, '', '']); (d.fills || []).slice(-4).reverse().forEach(f => ladder.push([f.side === 'buy' ? css('--dec') : css('--muted'), `${f.side === 'buy' ? 'Buy' : 'Sell'} · filled ${dhm(f.ts)}`, `${(+f.qty).toFixed(4)} @ ${f.price}`, 'filled', 'acc'])); if (p && p.exits && p.exits.stop_level) ladder.push([css('--dn'), 'Stop · ' + (p.exits.resting_stop === 'NONE' ? 'NOT RESTING' : 'resting'), `${p.exits.stop_level} · ${esc(p.exits.resting_stop)}`, p.exits.resting_stop === 'NONE' ? 'missing' : 'resting', p.exits.resting_stop === 'NONE' ? 'dn' : 'dn']);
  const ladderHtml = ladder.length ? ladder.map(([c, t, s, st, k]) => `<div class="row" style="display:grid;grid-template-columns:22px 1fr auto;gap:10px;align-items:center"><span class="dot" style="background:${c}"></span><div><div style="font-size:13px">${t}</div><div class="mono muted" style="font-size:11px">${s}</div></div>${st ? pill(st, k) : ''}</div>`).join('') : '<div class="dim">no orders on this name</div>';
  let optHtml = ''; const rd = d.option_read; const em = rd && rd.expiries && (rd.expiries.month || rd.expiries.near) ? (rd.expiries.month || rd.expiries.near).expected_move_pct : null;
  if (d.spread) { const L = occ(d.spread.long), S = occ(d.spread.short); const legs = d.spread_legs || []; const val = legs.length === 2 && legs[0].mid != null && legs[1].mid != null ? (legs[0].mid - legs[1].mid) : null; optHtml = card(`Held spread · ${L.h} / ${S.h}`, `<div style="display:flex;flex-direction:column;gap:10px"><div class="muted" style="font-size:12px">${d.spread.qty}x · entry ${d.spread.entry} · stop ${d.spread.stop} · target ${d.spread.target} · now ${val != null ? val.toFixed(2) : '?'} (${val != null ? pct((val / d.spread.entry - 1) * 100, 0) : ''}) · managed on net value by the watcher</div>${payoff({ type: L.type, longK: L.k, shortK: S.k, debit: d.spread.entry, spot: q.price || L.k, em, qty: d.spread.qty }, 560, 170)}</div>`, 'payoff at expiry'); }
  else if (d.is_option && d.contract && p) { const C = d.contract, cq = d.contract_quote || {}; optHtml = card(`Held contract · ${esc(sym)}`, `<div style="display:flex;flex-direction:column;gap:10px"><div class="tiles">${[['bid / ask', `${cq.bid ?? '–'} / ${cq.ask ?? '–'}`, 'indicative'], ['IV', cq.iv != null ? (cq.iv * 100).toFixed(1) + '%' : '–', ''], ['delta', cq.delta ?? '–', 'theta ' + (cq.theta ?? '–')], ['DTE', cq.dte ?? '–', 'exit by 3']].map(([l, v, s]) => `<div class="tile"><span class="l">${l}</span><span class="v">${esc(v)}</span><span class="s">${esc(s)}</span></div>`).join('')}</div>${payoff({ type: C.type === 'call' ? 'C' : 'P', longK: C.strike, debit: p.avg_entry, spot: q.price || C.strike, em, qty: Math.round(p.qty) }, 560, 170)}</div>`, 'payoff at expiry'); }
  else if (d.armed_preview && d.armed_preview.legs && d.armed_preview.legs.length) { const legs = d.armed_preview.legs, L = legs[0], S = legs[1]; optHtml = card(`Armed option · ${esc(d.armed_preview.note)}`, `<div style="display:flex;flex-direction:column;gap:10px"><div class="muted" style="font-size:12px"><b style="color:var(--gold)">Not held.</b> If the trigger fires, this is what the intent resolves to right now: ${legs.map(l => `${l.side} ${esc(occ(l.symbol).h)} (δ ${l.delta}, ${l.bid}/${l.ask})`).join(' · ')} at ~${d.armed_preview.limit} = $${(d.armed_preview.limit * 100).toFixed(0)} per spread, ${d.armed_preview.qty} contract(s).</div>${payoff({ type: L.symbol.match(OCC)[3], longK: L.strike, shortK: S ? S.strike : null, debit: d.armed_preview.limit, spot: q.price || L.strike, em, qty: d.armed_preview.qty || 1 }, 560, 170)}${rd ? `<div class="tiles">${[['IV 30d', rd.iv30_pct != null ? rd.iv30_pct + '%' : '–', 'vs realized ' + (rd.rv20_pct != null ? (+rd.rv20_pct).toFixed(1) + '%' : '–')], ['IV / RV', rd.iv_over_rv ?? '–', rd.premium_read || ''], ['expected move', em != null ? '±' + em + '%' : '–', (rd.expiries.month || rd.expiries.near || {}).exp || ''], ['skew 25δ', (rd.expiries.month || rd.expiries.near || {}).skew_25d_put_minus_call ?? '–', 'put − call']].map(([l, v, s]) => `<div class="tile"><span class="l">${l}</span><span class="v">${esc(String(v))}</span><span class="s">${esc(String(s))}</span></div>`).join('')}</div>` : ''}</div>`, 'preview, resolved at fire time'); }
  const dc = d.daily_context || {};
  v.innerHTML = topbar(esc(d.is_option ? occ(sym).h : sym), `${d.is_option ? 'option on ' + esc(d.underlying) : esc(dc.sector || '')}${dc.days_to_earnings != null ? ' · earnings in ' + dc.days_to_earnings + 'd' : ''}`) +
    `<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px"><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap"><a href="#/positions" class="muted" style="text-decoration:none;font-size:12px">${icon('chevron', 14)} positions</a>${d.thesis && d.thesis.grade ? pill(d.thesis.grade + ' catalyst', d.thesis.grade === 'confirmed' ? 'up' : 'gold', d.thesis.grade === 'confirmed' ? 'check' : null) : ''}${p ? pill('held', 'acc') : pill('not held')}${d.armed ? pill('armed ' + (d.armed.expression || 'stock').replace('_', ' '), 'gold') : ''}</div><div style="display:flex;align-items:baseline;gap:14px"><span class="disp" style="font-size:28px">${q.price != null ? '$' + q.price : ''}</span><span class="mono ${cls(q.chg_pct)}" style="font-size:13px">${q.chg_pct != null ? pct(q.chg_pct) + ' today' : ''}</span>${p ? `<span class="mono ${cls(p.pnl)}" style="font-size:13px">${money(p.pnl)} open P&amp;L</span>` : ''}</div></div>
    <div class="grid g21">${card('Price', `<div style="display:flex;flex-direction:column;gap:10px"><div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap"><span class="seg"><button class="${(state.tf || '1D') === '1D' ? 'on' : ''}" onclick="state.tf='1D';route()">1D</button><button class="${state.tf === '15m' ? 'on' : ''}" onclick="state.tf='15m';route()">15m</button></span><span class="dim" style="font-size:11px">levels from the journal: entry, resting stop, armed trigger, target</span></div>${state.tf === '15m' ? sparkLevels(d.bars_15m.map(b => b.c), 820, 260, levels, null, null) : candles(d.bars_daily, 820, 330, levels, marker)}</div>`, `${d.bars_daily.length} sessions · ${esc(d.underlying)}`)}${card('Orders on this name', ladderHtml, 'top to bottom = price ladder')}</div>
    <div class="grid g12">${optHtml || card('Options', `<div class="muted" style="font-size:12px">No option held or armed on this name.${rd ? ` Read: IV 30d ${rd.iv30_pct}% vs realized ${(+rd.rv20_pct || 0).toFixed(1)}% → ${esc(rd.premium_read || '')}; expected move ±${em}%.` : ''}</div>`)}${card('Thesis and plan', d.thesis && d.thesis.thesis ? md(`**Thesis.** ${d.thesis.thesis}\n\n**Target.** ${d.thesis.target || ''}\n\n**Stop.** ${d.thesis.stop || ''}\n\n**Horizon.** ${d.thesis.horizon || ''}`) : (d.armed ? md(`**Armed thesis.** ${d.armed.thesis}`) : '<div class="dim">no journaled thesis</div>'), d.thesis && d.thesis.ts ? 'journaled ' + dhm(d.thesis.ts) : '')}</div>
    ${card('Context', `<div class="tiles t6">${[['RSI 14', dc.rsi14], ['ATR %', dc.atr14_pct], ['vs 50d', dc.sma50_dist_pct != null ? pct(dc.sma50_dist_pct) : null], ['vs 52w high', dc.hi52_dist_pct != null ? pct(dc.hi52_dist_pct) : null], ['momentum', dc.mom_score], ['beta', dc.beta_spy]].map(([l, v]) => `<div class="tile"><span class="l">${l}</span><span class="v">${v == null ? '–' : (typeof v === 'number' ? v.toFixed(1) : esc(String(v)))}</span></div>`).join('')}</div>${d.decisions && d.decisions.length ? '<div style="margin-top:6px">' + d.decisions.slice(0, 6).map(x => `<div class="row" style="padding:6px 0"><div><b>${esc(x.kind)}</b> ${esc(x.side || '')} ${x.qty ?? ''} @ ${x.price ?? ''} <span class="muted" style="font-size:12px">${esc((x.thesis || JSON.parse(x.meta || '{}').reason || '').slice(0, 120))}</span></div>${pill(x.status, x.status === 'filled' ? 'up' : x.status === 'blocked' ? 'dn' : '')}</div>`).join('') + '</div>' : ''}`, 'daily screener + journal')}`;
}
async function sessions(v, id) {
  const [o, list] = await Promise.all([j('/api/overview'), j('/api/sessions?limit=40')]); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('sessions');
  const cur = id ? +id : (list[0] && list[0].id); const listHtml = list.map(s => `<div class="sess ${s.id === cur ? 'on' : ''}" onclick="location.hash='#/sessions/${s.id}'"><div style="display:flex;justify-content:space-between"><span class="mono" style="font-size:12.5px">#${s.id} <span class="muted">${esc(s.phase)}</span>${s.ended_at ? '' : ' <span class="gold">running</span>'}</span><span class="mono dim" style="font-size:11px">${hm(s.started_at)}</span></div><div class="dots">${(s.nodes || []).slice(0, 24).map(n => `<i style="background:${nodeColor(n.k)}"></i>`).join('')}</div><div class="muted" style="font-size:11px">${esc((s.actions || s.task || '').replace(/[*#]/g, '').slice(0, 90))}</div></div>`).join('');
  let detail = '<div class="dim">select a session</div>', facts = '';
  if (cur) { const d = await j('/api/sessions/' + cur); const s = d.session; const rows = d.trace.filter(t => !['system', 'status'].includes(t.kind)); const nodes = list.find(x => x.id === cur)?.nodes || [];
    const flow = rows.map(t => { let k = t.kind, title = '', body = '', pre = ''; if (k === 'prompt') { k = 'context'; title = 'session context (positions, plan, brief, task)'; pre = t.result; } else if (k === 'reasoning') { k = 'thinking'; title = 'thinking'; pre = t.result; body = esc((t.result || '').slice(0, 220)) + ((t.result || '').length > 220 ? '…' : ''); } else if (k === 'tool') { const res = t.result || ''; k = (res.startsWith('REJECTED') || res.startsWith('ERROR')) ? 'blocked' : (['buy_stock', 'sell_stock', 'buy_option', 'sell_option', 'open_spread', 'close_spread', 'arm_entry', 'disarm_entry', 'set_exit_levels', 'set_plan', 'set_world_brief', 'complete_task', 'record_lesson'].includes(t.name) ? 'decision' : 'tool'); title = t.name + ' ' + esc((t.args || '').slice(0, 90)); pre = 'args: ' + (t.args || '') + '\n\n' + res; body = esc(res.slice(0, 200).replace(/\n/g, ' ')) + (res.length > 200 ? '…' : ''); } else if (k === 'assistant') { title = 'message'; body = md(t.result); } else if (k === 'final') { title = 'summary'; body = md(t.result); }
      const col = k === 'context' ? css('--line') : nodeColor(k); return `<div class="tr"><span class="ts">${hm(t.ts)}</span><div class="spine"><i style="background:${col}"></i><b></b></div><div class="box ${k === 'final' || k === 'assistant' ? 'open' : ''}" style="border-left-color:${col}" onclick="this.classList.toggle('open')"><div class="h"><span><span class="k" style="color:${col}">${k}</span> <span class="t">${title}</span></span><span class="mono dim" style="font-size:11px">${t.secs ? t.secs + 's' : ''}</span></div>${body ? `<div class="body">${body}</div>` : ''}${pre ? `<pre>${esc(pre)}</pre>` : ''}</div></div>`; }).join('');
    detail = `<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px"><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap"><span class="disp" style="font-size:24px">#${s.id}</span>${pill(s.phase)}${s.task ? pill(s.task.startsWith('EVENT') ? 'event' : s.task.startsWith('SELF') ? 'self-assigned task' : s.task.startsWith('DUTY') ? 'duty' : 'operator task', 'gold') : ''}<span class="mono muted" style="font-size:12px">${hm(s.started_at)} → ${hm(s.ended_at) || 'running'} · ${s.tool_calls ?? '?'} tools · ${s.prompt_tokens ? (s.prompt_tokens / 1000).toFixed(1) + 'k tokens' : ''}</span></div>${legend()}</div>${card('Timeline', ribbon(nodes, 620, false), '', 'style="padding:12px 18px 6px"')}${s.task ? `<div class="muted" style="font-size:12px;padding:10px 12px;background:var(--surf);border:1px solid var(--line);border-radius:10px">${esc(s.task)}</div>` : ''}<div>${flow}</div>`;
    facts = card('Session facts', `<div class="mono muted" style="font-size:12px;display:flex;flex-direction:column;gap:5px"><div>tool calls <span style="color:var(--fg)">${s.tool_calls ?? '?'}</span></div><div>prompt <span style="color:var(--fg)">${s.prompt_tokens ?? '?'}</span> · completion ${s.completion_tokens ?? '?'} tokens</div><div>decisions: ${d.decisions.length}</div>${s.dry_run ? '<div class="gold">dry run</div>' : ''}</div>`) + (d.decisions.length ? card('Decisions', d.decisions.map(x => `<div class="row" style="padding:6px 0;display:block"><b>${esc(x.kind)}</b> ${esc(x.symbol)} ${esc(x.side || '')} ${x.qty ?? ''} @ ${x.price ?? ''} ${pill(x.status, x.status === 'filled' ? 'up' : x.status === 'blocked' ? 'dn' : '')}<div class="muted" style="font-size:11px">${esc((x.thesis || '').slice(0, 100))}</div></div>`).join('')) : ''); }
  v.innerHTML = topbar('Sessions', `${o.sessions_today} today`) + `<div class="grid g3s"><div class="card" style="padding:8px">${listHtml}</div><div style="display:flex;flex-direction:column;gap:12px">${detail}</div><div style="display:flex;flex-direction:column;gap:12px">${facts}</div></div>`;
}
async function brain(v) {
  const [o, w] = await Promise.all([j('/api/overview'), j('/api/world')]); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('brain');
  const reg = w.regime, b = reg ? reg.breadth : null; const tape = w.macro_tape || {}; const bls = w.bls || {};
  const tapeTiles = ['us10y_yield', 'wti_oil', 'gold', 'dollar_index', 'vix', 'es_futures', 'nq_futures', 'bitcoin'].filter(k => tape[k] && tape[k].last != null).map(k => `<div class="tile"><span class="l">${k.replace(/_/g, ' ')}</span><span class="v">${tape[k].last}</span><span class="s ${cls(tape[k].chg_1d_pct)}">${pct(tape[k].chg_1d_pct)} 1d${tape[k].chg_5d_pct != null ? ' · ' + pct(tape[k].chg_5d_pct) + ' 5d' : ''}</span></div>`).join('');
  const blsTiles = ['cpi', 'core_cpi', 'ppi', 'core_ppi', 'unemployment', 'payrolls'].filter(k => bls[k] && !bls[k].error).map(k => { const x = bls[k]; const v2 = k === 'unemployment' ? x.value + '%' : k === 'payrolls' ? (x.mom_change_thousands != null ? pct(x.mom_change_thousands, 0).replace('%', 'k') : x.value) : (x.mom_pct != null ? pct(x.mom_pct) + ' m/m' : x.value); return `<div class="tile"><span class="l">${k.replace('_', ' ')}</span><span class="v">${esc(String(v2))}</span><span class="s">${esc(x.latest_period || '')}${x.yoy_pct != null ? ' · ' + pct(x.yoy_pct) + ' y/y' : ''}</span></div>`; }).join('');
  const bh = (w.breadth_history || []).map(x => x.score).filter(x => x != null);
  const cal = (w.calendar || '').split('\n').filter(l => /^\d{4}-/.test(l)).slice(0, 8);
  v.innerHTML = topbar('Brain', 'state of the world · plan · queue · lessons · skills · library') +
    `<div class="card" style="display:grid;grid-template-columns:230px 1fr;gap:24px;align-items:start" id="hero">${reg ? `<div style="display:flex;flex-direction:column;gap:10px;align-items:flex-start"><img src="/assets/mascot-96.png?v=4" style="width:96px;height:96px;image-rendering:pixelated"><div class="disp muted" style="font-size:12px;letter-spacing:.06em;text-transform:uppercase">State of the world</div>${gauge(reg.score, 200)}<div class="disp" style="font-size:24px">${esc(reg.label)}</div><div class="dim" style="font-size:11px">table ${reg.table_age_h}h old · brief ${w.brief_ts ? dhm(w.brief_ts) : '–'}</div>${b ? [['above 50-day', b.pct_above_sma50], ['above 200-day', b.pct_above_sma200], ['RSI over 50', b.pct_rsi_gt_50]].map(([l, x]) => `<div style="display:grid;grid-template-columns:90px 1fr 40px;gap:8px;align-items:center;width:100%"><span class="muted" style="font-size:11px">${l}</span><div class="bar"><i style="width:${x}%;background:${x >= 60 ? css('--up') : x <= 40 ? css('--dn') : css('--gold')}"></i></div><span class="mono" style="font-size:11px;text-align:right">${x}%</span></div>`).join('') : ''}${bh.length > 1 ? `<div style="width:100%"><div class="dim" style="font-size:11px">regime score · ${bh.length} days</div>${lineChart(bh, 230, 44, css('--series'), 50)}</div>` : ''}</div>` : '<div class="dim">screener not built</div>'}<div style="display:flex;flex-direction:column;gap:14px"><div class="dials">${(w.dials || []).map(d => dial(d, false)).join('') || '<div class="dim">tape unavailable</div>'}</div>${eventChips(w.next_events)}${md(w.brief || '_No world brief yet._')}</div></div>
    <div class="grid g11">${card('Sectors · 20-day', w.sectors && w.sectors.length ? hbars(w.sectors.map(s => ({ label: s.sector, v: s.chg_20d })), 'v', x => pct(x, 1)) : '<div class="dim">no sector data</div>', 'average of members')}${card('Macro tape', `<div class="tiles">${tapeTiles || '<div class="dim">unavailable</div>'}</div>`, esc(tape.as_of || ''))}</div>
    <div class="grid g11">${card('Latest prints', `<div class="tiles" style="grid-template-columns:repeat(3,minmax(0,1fr))">${blsTiles || '<div class="dim">unavailable</div>'}</div>`, esc(bls.source || 'BLS'))}${card('Calendar', (cal.length ? cal.map(l => `<div class="row" style="padding:6px 0;font-size:12px"><span class="mono">${esc(l)}</span></div>`).join('') : '<div class="dim">no scheduled releases parsed</div>') + (w.fed && w.fed.length ? `<div class="dim" style="font-size:11px;margin-top:6px">Fed: ${w.fed.slice(0, 2).map(f => esc(f.date + ' ' + f.title)).join(' · ')}</div>` : ''), 'BLS schedule + Fed')}</div>
    <div class="grid g111">${card('Plan', md(w.plan || '_No plan yet._'), w.plan_ts ? dhm(w.plan_ts) : '')}${card('Task queue', (w.tasks_open || []).length ? w.tasks_open.map(t => `<div class="row" style="padding:6px 0;display:flex;gap:8px;align-items:flex-start"><span class="mono dim" style="font-size:11px">#${t.id}</span>${pill(t.kind, 'gold', t.kind === 'experiment' ? 'flask' : 'search')}${pill('p' + t.priority)}<span class="muted" style="font-size:12px">${esc(t.text.slice(0, 160))}</span></div>`).join('') : '<div class="dim">queue empty</div>', (w.tasks_open || []).length + ' open')}${card('Lessons', (w.lessons || []).map(l => `<div class="row" style="padding:6px 0;display:flex;gap:8px">${icon('check', 14, css('--up'))}<span class="muted" style="font-size:12px">${esc(l.text)}</span></div>`).join('') || '<div class="dim">none</div>', (w.lessons || []).length + ' rules')}</div>${card('Skills', (w.skills || []).length ? `<div class="lib">${w.skills.map(k => `<div class="row" style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><span class="t">${esc(k.name)}</span> ${pill(k.source === 'repo' ? 'operator' : 'agent', k.source === 'repo' ? '' : 'violet')}${pill(k.status, k.status === 'active' ? 'up' : 'gold')}${k.enabled ? '' : pill('disabled', 'dn')}<div class="muted" style="font-size:12px">${esc(k.description)}</div><div class="dim mono" style="font-size:10.5px">${k.chars} chars${k.scripts.length ? ' · scripts ' + esc(k.scripts.join(', ')) : ''}${k.resources.length ? ' · resources ' + esc(k.resources.join(', ')) : ''}</div></div><div style="display:flex;gap:6px;flex-shrink:0">${k.source === 'agent' && k.status === 'draft' ? `<button class="btn pri" onclick="skillAction('${esc(k.name)}','approve')">Approve</button>` : ''}<button class="btn" onclick="skillAction('${esc(k.name)}','${k.enabled ? 'disable' : 'enable'}')">${k.enabled ? 'Disable' : 'Enable'}</button>${k.source === 'agent' ? `<button class="btn dngr" onclick="skillAction('${esc(k.name)}','delete')">Delete</button>` : ''}</div></div>`).join('')}${(w.skills_errors || []).length ? `<div class="dn" style="font-size:12px">${esc(w.skills_errors.join('; '))}</div>` : ''}</div>` : '<div class="dim">no skills installed · add folders under skills/</div>', (w.skills || []).filter(k => k.status === 'active' && k.enabled).length + ' active · agent drafts need approval')}${card('Library', (w.knowledge || []).length ? `<div class="lib">${w.knowledge.map(k => `<div class="row"><span class="t">${esc(k.title)}</span> <span class="dim mono" style="font-size:10.5px">${esc((k.updated || '').slice(0, 10))}</span><div class="muted" style="font-size:12px">${esc(k.summary)}</div></div>`).join('')}</div>` : '<div class="dim">nothing studied yet · off-hours study sessions fill this in</div>', (w.knowledge || []).length + ' topics · study mode ' + (w.study ? (w.study.enabled ? w.study.done_today + '/' + w.study.per_night + ' tonight' : 'off') : ''))}`;
  if (innerWidth < 900) { const h = $('#hero'); if (h) h.style.gridTemplateColumns = '1fr'; document.querySelectorAll('.dials:not(.compact)').forEach(d => d.style.gridTemplateColumns = '1fr'); }
}
async function journal(v) {
  const o = await j('/api/overview'); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('journal'); const what = state.jwhat || 'decisions'; const d = await j('/api/journal?what=' + what + '&limit=80'); let body = '';
  if (what === 'decisions') body = d.rows.map(r => `<div class="row" style="align-items:flex-start"><span class="mono dim" style="font-size:11px;min-width:40px;padding-top:3px">${hm(r.ts)}</span><div style="flex-grow:1"><b>${esc(r.kind)}</b> ${esc(r.symbol_h)} ${esc(r.side || '')} ${r.qty ?? ''} @ ${r.price ?? ''} ${r.meta.catalyst_grade ? pill(r.meta.catalyst_grade, 'acc') : ''}<div class="muted" style="font-size:12px">${esc(r.thesis || r.meta.reason || '')}</div>${r.meta.violations ? `<div class="dn" style="font-size:12px">${esc(r.meta.violations.join('; '))}</div>` : ''}</div>${pill(r.status, r.status === 'filled' ? 'up' : r.status === 'blocked' ? 'dn' : '')}</div>`).join('');
  else if (what === 'trades') body = `<div class="mono muted" style="font-size:12px;margin-bottom:8px">${esc(JSON.stringify(d.stats))}</div>` + d.rows.map(r => `<div class="row"><div><b>${esc(occ(r.symbol) ? occ(r.symbol).h : r.symbol)}</b><div class="mono dim" style="font-size:11px">${dhm(r.opened_at)} → ${dhm(r.closed_at)} · ${r.qty} @ ${r.entry} → ${r.exit}</div></div><div class="mono ${cls(r.pnl)}">${money(r.pnl)} <span class="dim" style="font-size:11px">${pct(r.pnl_pct)}</span></div></div>`).join('') || '<div class="dim">no completed round trips yet</div>';
  else body = d.rows.map(r => `<div class="row" style="font-size:12px"><span class="mono dim" style="font-size:11px;min-width:40px">${(r.ts || '').slice(5, 16).replace('T', ' ')}</span>${r.kind ? pill(r.kind, r.kind === 'event' ? 'acc' : r.kind === 'error' ? 'dn' : '') : ''}<span class="muted" style="flex-grow:1">${esc(r.text)}</span></div>`).join('') || '<div class="dim">nothing yet</div>';
  v.innerHTML = topbar('Journal', 'decisions, trades, lessons, notes, events') + `<div class="seg">${['decisions', 'trades', 'lessons', 'notes', 'events'].map(x => `<button class="${x === what ? 'on' : ''}" onclick="state.jwhat='${x}';route()">${x}</button>`).join('')}</div>` + card(what, body);
}
async function config(v) {
  const [o, st, c, llm, tg] = await Promise.all([j('/api/overview'), j('/api/style'), j('/api/config'), j('/api/config/llm'), j('/api/telegram').catch(() => null)]); state.style = o.style; state.daemon = o.daemon; state.halted = o.halted; renderNav('config');
  const presets = Object.entries(st.styles).map(([k, s]) => `<div class="preset st-${k} ${k === st.active ? 'on' : ''}" onclick="setStyle('${k}')"><div style="display:flex;justify-content:space-between;align-items:center"><span class="n">${esc(s.label)}</span>${k === st.active ? pill('active', 'acc') : ''}</div><div class="muted" style="font-size:12px">${esc(s.tagline)}</div><ul style="margin:0;padding-left:16px">${s.summary.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>`).join('');
  const provs = [['tavily', 'Tavily', 'web + news search; returns page text'], ['finnhub', 'Finnhub', 'company news, earnings calendar, metrics'], ['brave', 'Brave', 'second web engine (not wired yet)'], ['searxng', 'SearXNG', 'self-hosted fallback']].map(([p, n, d]) => { const s = c[p]; return `<div class="row" style="display:block"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><span class="sym sm">${n}</span>${pill(s.active ? 'active' : s.enabled_flag ? (s.has_key ? 'active' : 'no key') : 'disabled', s.active ? 'up' : '')}<span class="muted" style="font-size:12px">${d}</span></div>${p !== 'searxng' ? `<div class="mono muted" style="font-size:11px;margin-top:4px">key ${esc(s.key_masked || 'not set')} · used ${s.usage_month}${s.budget ? ' / ' + s.budget : ''} this month</div><div style="display:flex;gap:6px;margin-top:6px;flex-wrap:wrap"><input id="key-${p}" type="password" class="field" placeholder="paste API key" style="flex:1;min-width:160px"><button class="btn pri" onclick="setKey('${p}')">Save</button>${s.has_key ? `<button class="btn" onclick="clearKey('${p}')">Clear</button>` : ''}<button class="btn" onclick="toggleProv('${p}',${!s.enabled_flag})">${s.enabled_flag ? 'Disable' : 'Enable'}</button><button class="btn" onclick="testProv('${p}')">Test</button><span id="test-${p}" class="dim" style="font-size:12px;align-self:center"></span></div>` : `<div style="display:flex;gap:6px;margin-top:6px"><button class="btn" onclick="toggleProv('${p}',${!s.enabled_flag})">${s.enabled_flag ? 'Disable' : 'Enable'}</button><button class="btn" onclick="testProv('${p}')">Test</button><span id="test-${p}" class="dim" style="font-size:12px;align-self:center"></span></div>`}</div>`; }).join('');
  const opts = Object.keys(llm.presets).map(k => `<option value="${k}" ${k === llm.provider ? 'selected' : ''}>${k} — ${esc(llm.presets[k].note)}</option>`).join('');
  v.innerHTML = topbar('Config', 'trading style · model · appearance · providers · safety') +
    card('Trading style', `<div style="display:flex;flex-direction:column;gap:12px"><div class="muted" style="font-size:12px">Changes the risk envelope, instruments and tempo from the next session on. The rules below never change.</div><div class="grid g111">${presets}</div><div><div class="disp muted" style="font-size:12px;letter-spacing:.06em;text-transform:uppercase;margin-bottom:6px">Fixed in every style</div><ul style="margin:0;padding-left:18px;font-size:12px;color:var(--muted)">${st.fixed_rules.map(r => `<li>${esc(r)}</li>`).join('')}</ul></div></div>`, 'active: ' + esc(st.active)) +
    `<div class="grid g12">${card('Model', `<div style="display:flex;flex-direction:column;gap:8px"><div class="muted" style="font-size:12px">Any OpenAI-compatible chat server with tool calling. Applies to the next session; no restart. Key goes to .env.</div><select id="llm-prov" class="field">${opts}</select><input id="llm-url" class="field" value="${esc(llm.base_url)}" placeholder="base URL"><input id="llm-model" class="field" value="${esc(llm.model)}" placeholder="model id"><div style="display:flex;gap:6px;flex-wrap:wrap"><input id="llm-key" type="password" class="field" style="flex:1;min-width:160px" placeholder="API key (optional) — ${llm.key_masked ? 'set: ' + esc(llm.key_masked) : 'not set'}"><label class="muted" style="font-size:12px;display:flex;align-items:center;gap:4px"><input id="llm-re" type="checkbox" ${llm.send_reasoning_effort ? 'checked' : ''}>send reasoning_effort</label></div><div style="display:flex;gap:6px;align-items:center"><button class="btn pri" onclick="llmSave()">Save</button><button class="btn" onclick="llmTest()">Test</button><span id="llm-test" class="dim" style="font-size:12px"></span></div><div class="mono dim" style="font-size:11px">context window ${llm.context ? (llm.context.tokens ? llm.context.tokens.toLocaleString() + ' tokens (' + esc(llm.context.source) + ')' : 'unknown (' + esc(llm.context.source) + ')') : '?'} → budget ${Math.round((llm.context ? llm.context.effective_chars : llm.context_char_budget) / 1000)}k chars, tool results ≤ ${llm.context ? llm.context.tool_result_chars : llm.tool_result_max_chars} chars${llm.context && llm.context.warning ? ` · <span class="dn">${esc(llm.context.warning)}</span>` : ''}</div><div class="mono dim" style="font-size:11px">reasoning by phase ${esc(JSON.stringify(llm.reasoning_by_phase))} · tool budget ${llm.max_tool_calls}</div></div>`, 'hot-swappable')}
    ${card('Appearance', `<div style="display:flex;flex-direction:column;gap:10px"><span class="seg">${[['dark', 'moon'], ['light', 'sun'], ['system', 'monitor']].map(([m, i]) => `<button class="${themeMode === m ? 'on' : ''}" onclick="themeMode='${m}';applyTheme('${m}');route()">${icon(i, 13)} ${m}</button>`).join('')}</span><div class="muted" style="font-size:12px">System follows the OS setting. Charts use a palette validated for each theme.</div></div>`, 'dark · light · system') + card('Safety', `<div style="display:flex;flex-direction:column;gap:10px;font-size:12.5px;color:var(--muted)"><div style="display:flex;justify-content:space-between;align-items:center"><span>Kill switch</span><button class="halt" onclick="armKill()">${icon('shield', 14)}${state.halted ? 'Resume' : 'Halt new entries'}</button></div><div style="display:flex;justify-content:space-between"><span>Dashboard token</span>${c.token_protected ? pill('set', 'up') : pill('not set · LAN open', 'dn')}</div><div style="display:flex;justify-content:space-between"><span>Daemon</span>${pill(state.daemon, state.daemon === 'active' ? 'up' : 'dn')}</div></div>`)}</div>` +
    (tg ? card('Telegram', `<div style="display:flex;flex-direction:column;gap:10px;font-size:12.5px"><div class="muted">Alerts to your phone (fills, armed fires, errors, broker trouble, pre/post-market summaries) and a command channel: /status, /halt, /style, /disarm, or plain text as a request the next session answers. Create a bot with @BotFather, paste its token here, then pair your chat with a one-time code.</div><div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center"><input id="key-telegram" type="password" class="field" placeholder="bot token ${tg.token_masked ? '(set: ' + esc(tg.token_masked) + ')' : ''}" style="flex:1;min-width:200px"><button class="btn pri" onclick="setKey('telegram')">Save</button>${tg.configured ? `<button class="btn" onclick="clearKey('telegram')">Clear</button>` : ''}</div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span>Paired chats: ${tg.chat_ids.length ? tg.chat_ids.map(id => `<span class="pill up">${id} <a href="#" onclick="tgAction('unpair',{chat_id:${id}});return false" style="color:inherit">×</a></span>`).join(' ') : pill('none', 'dn')}</span><button class="btn" onclick="tgAction('pair')" ${tg.configured ? '' : 'disabled'}>Generate pairing code</button>${tg.pair_code ? `<span>send <code>/pair ${esc(tg.pair_code)}</code> to your bot within 10 minutes</span>` : ''}<button class="btn" onclick="tgAction('test')" ${tg.chat_ids.length ? '' : 'disabled'}>Test</button><span id="tg-test" class="dim"></span></div><div style="display:flex;gap:14px;flex-wrap:wrap">${Object.entries(tg.kinds).map(([k, d]) => `<label class="muted" style="display:flex;gap:4px;align-items:center" title="${esc(d)}"><input type="checkbox" ${tg.notify[k] ? 'checked' : ''} onchange="tgAction('notify',{kind:'${k}',on:this.checked})">${k}</label>`).join('')}${tg.muted_until && tg.muted_until * 1000 > Date.now() ? `<span class="gold">muted until ${new Date(tg.muted_until * 1000).toLocaleTimeString()} <a href="#" onclick="tgAction('unmute');return false">unmute</a></span>` : ''}</div></div>`, tg.configured ? (tg.chat_ids.length ? 'active' : 'token set · pair a chat') : 'not configured') : '') +
    card('Providers', provs + `<div class="row" style="display:block"><div class="muted" style="font-size:12px;margin-bottom:6px">Search chain: first provider with results wins; news queries merge the first two (${c.merge_news ? 'on' : 'off'}).</div><div style="display:flex;gap:6px"><input id="order" class="field" value="${esc(c.order.join(', '))}"><button class="btn pri" onclick="setOrder()">Save</button></div></div>`, 'chain: ' + esc(c.order.join(' → ')));
}
async function tgAction(action, extra) { try { const d = await post('/api/telegram', Object.assign({ action }, extra || {})); if (action === 'test') { const el = $('#tg-test'); if (el) el.textContent = d.detail; return; } route(); } catch (e) { alert(e.message); } }
async function skillAction(name, action) { if (action === 'delete' && !confirm('Delete draft skill ' + name + '?')) return; try { await post('/api/skills', { name, action }); route(); } catch (e) { alert(e.message); } }
async function setKey(p) { const v = $('#key-' + p).value.trim(); if (!v) return; try { await post('/api/config', { action: 'set_key', provider: p, value: v }); route(); } catch (e) { alert(e.message); } }
async function clearKey(p) { if (!confirm('Clear the ' + p + ' key?')) return; await post('/api/config', { action: 'set_key', provider: p, value: '' }); route(); }
async function toggleProv(p, en) { await post('/api/config', { action: 'toggle', provider: p, enabled: en }); route(); }
async function testProv(p) { const el = $('#test-' + p); el.textContent = 'testing…'; const d = await post('/api/config/test', { provider: p }); el.innerHTML = (d.ok ? '<span class="ok">ok</span> ' : '<span class="err">fail</span> ') + esc(d.detail); }
async function setOrder() { await post('/api/config', { action: 'order', order: $('#order').value.split(',').map(x => x.trim()).filter(Boolean) }); route(); }
async function llmSave() { const body = { provider: $('#llm-prov').value, base_url: $('#llm-url').value.trim(), model: $('#llm-model').value.trim(), send_reasoning_effort: $('#llm-re').checked }; const k = $('#llm-key').value.trim(); if (k) body.api_key = k; try { await post('/api/config/llm', body); route(); } catch (e) { alert(e.message); } }
async function llmTest() { const el = $('#llm-test'); el.textContent = 'testing…'; const d = await post('/api/config/llm/test', {}); el.innerHTML = d.ok ? `<span class="ok">ok</span> ${esc(d.model)} · tools ${d.tool_calls ? 'yes' : 'NO'} · ${d.secs}s` : `<span class="err">fail</span> ${esc(d.detail || '')}`; }

/* ---------- router ---------- */
async function route() {
  const v = $('#view'); const [, r = 'overview', arg] = location.hash.replace(/^#\/?/, '').split('/').length ? ['', ...location.hash.replace(/^#\/?/, '').split('/')] : [];
  try { if (r === 'positions' && arg) await position(v, decodeURIComponent(arg)); else if (r === 'positions') await positions(v); else if (r === 'sessions') await sessions(v, arg); else if (r === 'brain') await brain(v); else if (r === 'journal') await journal(v); else if (r === 'config') await config(v); else await overview(v); }
  catch (e) { v.innerHTML = `<div class="card err">${esc(e.message)}</div>`; console.error(e); }
  window.scrollTo(0, 0);
}
addEventListener('hashchange', route); route();
setInterval(() => { if ((location.hash || '#/overview').startsWith('#/overview')) route(); }, 60000);
